name: sludge

on:
  schedule:
    - cron: '0 */11 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goblin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: yoink
        env:
          KEY: "000000000001"
        run: curl -s "https://bluefrog.nextpanel.com/api/v1/${KEY}/token" | jq -r '.token' > meat

      - name: rot
        run: |
          git config user.email void@void.void
          git config user.name void
          git add meat
          git diff --quiet || git commit -m "rot $(date -u +%FT%TZ)"
          git push
